assert = require('assert');
util = require('util');
spawn = require('child_process').spawn;
exec = require('child_process').exec;
path = require('path');
examples = path.resolve(__dirname, '../example');
request = require('request').defaults({jar: true});
idgen = require('idgen');
rimraf = require('rimraf');
ncp = require('ncp').ncp;
fs = require('fs');
yaml = require('js-yaml');
mkdirp = require('mkdirp');
middler = require('middler');
prompt = require('cli-prompt');
commander = require('commander');
port = process.env.MOTLEY_PORT
