afterware: "*_afterware.js"
collections: "*_collection.js"
controllers: "*_controller.js"
middleware: "*_middleware.js"
plugins: "*_plugin.js"
public: "*.css"
views: "*.hbs"
port: 3000
title: new motley gist
