afterware: "*_afterware.js"
collections: "*_collection.js"
controllers: "*_controller.js"
middleware: "*_middleware.js"
plugins: "*_plugin.js"
public:
  - "*.css"
  - "*.jpg"
  - "*.jpeg"
  - "*.gif"
  - "*.ico"
  - "*.png"
  - "*.csv"
  - "*.pdf"
  - "*.mid"
  - "*.woff"
  - "*.otf"
  - "*.svg"
  - "*.svgz"
  - "*.txt"
views: "{*.hbs,*.handlebars,*.md,*.markdown"
port: 3000
title: new motley gist
